"use client";

import React from "react";
import { useNotifications } from "@/hooks/useNotifications";
import { Breadcrumb, Button, Badge } from "@/components/ui";
import { DataTable } from "@/components/tables";
import { Card, MetricCard } from "@/components/cards";
import { MOCK_REPORTS } from "@/mocks/reports";
import { ChartBar as BarChart2, Plus, Download, FileText, TrendingUp, Clock, CircleCheck as CheckCircle2 } from "lucide-react";

export default function ReportsPage() {
  const { addToast } = useNotifications();

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="space-y-1">
          <Breadcrumb items={[{ name: "Workspace", href: "/workspace/dashboard" }, { name: "Reports" }]} />
          <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600/15 border border-blue-500/30">
              <BarChart2 className="w-4 h-4 text-blue-400" />
            </span>
            <span>Practice Management Reports</span>
          </h1>
          <p className="text-xs text-slate-400">Generate and review legal audits, workload balance, and invoice summaries.</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="secondary"
            leftIcon={<Download className="w-4 h-4" />}
            onClick={() => addToast("Export Reports", "Report archive bundle exported.", "success")}
          >
            Export Archive
          </Button>
          <Button
            variant="primary"
            leftIcon={<Plus className="w-4 h-4" />}
            onClick={() => addToast("Report Generation", "Compilation engine launched in background.", "info")}
          >
            Generate Report
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard title="Reports (30d)" value={MOCK_REPORTS.length} info="Generated" trend="up" />
        <MetricCard title="Scheduled" value="3" info="Recurring" trend="neutral" />
        <MetricCard title="Avg Compile" value="4.2s" info="Per report" trend="neutral" />
        <MetricCard title="Shared" value="12" info="Distributed" trend="up" change="+4" />
      </div>

      {/* Quick templates */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { icon: FileText, label: "Financial", desc: "Revenue & invoices", color: "text-emerald-400" },
          { icon: TrendingUp, label: "Productivity", desc: "Billable hours", color: "text-blue-400" },
          { icon: Clock, label: "Matter Velocity", desc: "Stage durations", color: "text-amber-400" },
          { icon: CheckCircle2, label: "Team Workload", desc: "Capacity reports", color: "text-indigo-400" },
        ].map((r) => {
          const Icon = r.icon;
          return (
            <div key={r.label} className="group flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950/40 p-4 hover:border-slate-700 hover:bg-slate-900/60 transition-all cursor-pointer">
              <Icon className={`w-5 h-5 ${r.color}`} />
              <div>
                <div className="text-xs font-bold text-white">{r.label}</div>
                <div className="text-[10px] text-slate-500 mt-0.5">{r.desc}</div>
              </div>
            </div>
          );
        })}
      </div>

      <DataTable
        title="Archived Reports"
        data={MOCK_REPORTS}
        columns={[
          { header: "Report Title", accessor: (r) => <span className="font-bold text-white">{r.title}</span> },
          { header: "Report Category", accessor: (r) => <Badge label={r.type} variant="info" /> },
          { header: "Generated By", accessor: (r) => <span>{r.generatedBy}</span> },
          { header: "Timestamp", accessor: (r) => <span className="text-slate-400">{new Date(r.createdAt).toLocaleString()}</span> },
        ]}
      />
    </div>
  );
}
