"use client";

import React from "react";
import { useNotifications } from "@/hooks/useNotifications";
import { Breadcrumb, Button, Badge } from "@/components/ui";
import { DataTable } from "@/components/tables";
import { MOCK_REPORTS } from "@/mocks/reports";
import { BarChart2, Plus } from "lucide-react";

export default function ReportsPage() {
  const { addToast } = useNotifications();

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="space-y-1">
          <Breadcrumb items={[{ name: "Workspace", href: "/workspace/dashboard" }, { name: "Reports" }]} />
          <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <BarChart2 className="w-5 h-5 text-blue-500" />
            <span>Practice Management Reports</span>
          </h1>
          <p className="text-xs text-slate-400">Generate and review legal audits, workload balance, and invoice summaries.</p>
        </div>
        <Button
          variant="primary"
          leftIcon={<Plus className="w-4 h-4" />}
          onClick={() => addToast("Report Generation", "Compilation engine launched in background.", "info")}
        >
          Generate Report
        </Button>
      </div>

      <DataTable
        title="Archived Reports"
        data={MOCK_REPORTS}
        columns={[
          { header: "Report Title", accessor: (r) => <span className="font-bold text-white">{r.title}</span> },
          { header: "Report Category", accessor: (r) => <Badge label={r.type} variant="info" /> },
          { header: "Generated By", accessor: (r) => <span>{r.generatedBy}</span> },
          { header: "Timestamp", accessor: (r) => <span className="text-slate-400">{new Date(r.createdAt).toLocaleString()}</span> }
        ]}
      />
    </div>
  );
}
